# Generated by Django 4.0.3 on 2022-07-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_reviews',
            new_name='slider',
        ),
    ]
