# Generated by Django 4.0.3 on 2022-07-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_product_reviews_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='sims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('email1', models.CharField(max_length=200)),
                ('email2', models.CharField(max_length=200)),
                ('contact1', models.CharField(max_length=200)),
                ('contact2', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('whatsapp1', models.CharField(max_length=200)),
                ('whatsapp2', models.CharField(max_length=200)),
                ('science_std', models.CharField(max_length=200)),
                ('commerce_std', models.CharField(max_length=200)),
                ('total_teacher', models.CharField(max_length=200)),
                ('graduate_std', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
