# Generated by Django 4.0.3 on 2022-07-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_leader_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='address',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='email',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='mobile',
        ),
    ]
