# Generated by Django 4.0.3 on 2022-08-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_faculties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='image',
            field=models.ImageField(upload_to='academics/faculties'),
        ),
    ]
