# Generated by Django 4.0.3 on 2022-08-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_infrastructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='information',
        ),
    ]
