# Generated by Django 4.0.3 on 2022-08-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_tbl_rc_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rc_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regd_no', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('aadhaar', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('doj', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('father_mobile', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('mother_mobile', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_relation', models.CharField(max_length=100)),
                ('guardian_mobile', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('school_marks', models.CharField(max_length=100)),
                ('school_info', models.CharField(max_length=200)),
                ('present_address', models.CharField(max_length=200)),
                ('permanent_address', models.CharField(max_length=200)),
                ('aadhaar_card', models.ImageField(upload_to='students/aadhaar_card')),
                ('std_photo', models.ImageField(upload_to='students/photo')),
                ('std_document', models.ImageField(upload_to='students/documents')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
