# Generated by Django 4.0.3 on 2022-08-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_tbl_rc_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rc_std_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
                ('mode', models.CharField(max_length=500)),
                ('remarks', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
