# Generated by Django 4.0.3 on 2022-08-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_tbl_rc_std_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_rc_std_payments',
            name='invoice',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tbl_rc_std_payments',
            name='txn_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
