# Generated by Django 4.0.3 on 2022-08-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_tbl_rc_std_payments_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_rc_students',
            name='doj',
            field=models.DateField(),
        ),
    ]
