# Generated by Django 4.0.3 on 2022-08-24 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_tbl_rc_students_doj'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_rc_students',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_rc_students',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
