# Generated by Django 4.0.3 on 2022-08-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_tbl_sc_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_rc_std_payments',
            name='date',
            field=models.DateField(),
        ),
    ]
