# Generated by Django 4.0.3 on 2022-09-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_tbl_rc_std_payments_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sc_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('aadhaar', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('doj', models.DateField()),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_email', models.CharField(max_length=100)),
                ('guardian_mobile', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('matriculation_board', models.CharField(max_length=100)),
                ('exceptation_marks', models.CharField(max_length=100)),
                ('std_photo', models.ImageField(upload_to='summer/photo')),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
