# Generated by Django 4.0.3 on 2022-09-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_tbl_sc_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sc_std_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.CharField(max_length=100)),
                ('txn_id', models.CharField(max_length=100)),
                ('invoice', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
