# Generated by Django 4.0.3 on 2022-09-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_delete_tbl_sc_std_payments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_sc_students',
        ),
    ]
