# Generated by Django 4.0.3 on 2022-09-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_delete_tbl_sc_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_sc_stream',
        ),
    ]
