# Generated by Django 4.0.3 on 2022-09-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_delete_tbl_rc_std_payments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rc_students',
        ),
    ]
